rules:
  comma-dangle:
    - 0
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-empty:
    - 0
  no-unused-vars:
    - 2
    - args: all
      argsIgnorePattern: ^_
  keyword-spacing:
    - 2
  space-before-function-paren:
    - 2
    - anonymous: always
      named: never

env:
  browser: true
  node: true

globals:
  zip: true
  Vue: true
  CodeMirror: true
  Promise: true

extends: 'eslint:recommended'
