rules:
  no-undef:
    - 0
  no-unused-vars:
    - 0
  comma-dangle:
    - 0
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-empty:
    - 0

env:
  browser: true
  es6: true

extends: 'eslint:recommended'
